export enum ActionType {
  SIGN_UP = 0,
  UPDATE_PROFILE = 1,
  FINISH_FAST_SURVEY = 2,
  FINISH_HEALTH_SURVEY = 3,
  FINISH_SURVEY = 4,
  ADVISE_REQUEST = 5,
  COMPLAINT_REQUEST = 6,
  READ_EXERCISE_GUIDE = 7,
  FIRST_UPDATE_PROFILE = 8,
  RECOMMEND_APP = 9,
}
